[package]
name = "devops-takehome"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"

[[bin]]
name = "devops-takehome"
path = "src/main.rs"

[lib]
name = "devops_takehome"
path = "src/lib.rs"
